// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfnHogMqpLrTMngJo7GCwVVPu407c328',
    appId: '1:717166661497:web:9deca0ed58272e4eff29a8',
    messagingSenderId: '717166661497',
    projectId: 'emeaproject-a72a5',
    authDomain: 'emeaproject-a72a5.firebaseapp.com',
    storageBucket: 'emeaproject-a72a5.appspot.com',
    measurementId: 'G-FM8SKQBEBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgj5O5qgUePN18pM_DWUiKPKk1_e0Vprk',
    appId: '1:717166661497:android:50f6857a66086810ff29a8',
    messagingSenderId: '717166661497',
    projectId: 'emeaproject-a72a5',
    storageBucket: 'emeaproject-a72a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn7pdP3vBoJSZW032eGrACxS_iRHXdwl8',
    appId: '1:717166661497:ios:7792f74155b26a98ff29a8',
    messagingSenderId: '717166661497',
    projectId: 'emeaproject-a72a5',
    storageBucket: 'emeaproject-a72a5.appspot.com',
    iosClientId: '717166661497-v8unl5n1neuub93c3epbf1odvitgcil7.apps.googleusercontent.com',
    iosBundleId: 'com.example.oopleproject',
  );
}
